### ISSUE TITLE
coreutils `mktemp` break install on macos

### ISSUE THREAD

**Issue by yqrashawn** [smashedtoatoms/asdf-sbcl#12]
**Describe the bug**

`mktemp: too few X's in template ‘asdf-sbcl’` when `mktemp` got override by user

maybe hard code the path `/usr/bin/mktemp` will help, not sure if it's the case for all macos device

**Steps to reproduce**
`asdf install sbcl 2.3.1`

**Expected behavior**
...

**Screenshots**

```
❯ asdf install sbcl 2.3.1
mktemp: too few X's in template ‘asdf-sbcl’
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   402  100   402    0     0    738      0 --:--:-- --:--:-- --:--:--   744
100   371  100   371    0     0    360      0  0:00:01  0:00:01 --:--:--  1325
Warning: Failed to create the file /bootstrap.tar.bz2: Read-only file system
  0 8988k    0  8063    0     0   6267      0  0:24:28  0:00:01  0:24:27  6267
curl: (23) Failure writing output to destination
mkdir: cannot create directory ‘/bootstrap-installer’: Read-only file system
tar: Error opening archive: Failed to open '/bootstrap.tar.bz2'
```

**Additional context**

**Comment by smashedtoatoms** [comment]
I don't understand why it is trying to install into root.  That's why it is complaining that it is a Read-only filesystem.  The script installs into /tmp/bootstrap-installer, but for some reason, the TEMP_DIR, CACHE_DIR environment variables appear to not get set on your machine.  I will see if I can simulate this on my machine; however, until I can simulate it and understand what is happening on your machine, I won't be able to modify the installer.  What version of MacOS are you running and what type of mac do you have?

**Comment by yqrashawn** [comment]
> TEMP_DIR, CACHE_DIR environment variables appear to not get set on your machine.

is caused by `mktemp: too few X's in template ‘asdf-sbcl’`
cause the `mktemp` in my `PATH` is from [coreutils](https://www.gnu.org/software/coreutils/) rather than the default one macos at `/usr/bin/mktemp`

**Comment by smashedtoatoms** [comment]
Ok, I am making the executive decision that this isn't a bug.  Here is my rationale.  You've chosen to install coreutils into your PATH in a way where it overrides the standard tools.  I don't know your reasons, but it does make your config unique, and I can't realistically build workarounds for every custom config.  I don't want to hard-code it because that removes the ability for users to override it if they want or need to for some reason I haven't thought of.  It would be more realistic to ask you, the user who has opted out of standard tooling, to symlink in the standard tooling or update your PATH when installing SBCL using asdf-vm.

I apologize because I know this is not the answer you want to hear.  There are more significant downsides to changing the existing behavior that everyone relies upon today to accommodate one bespoke config, though.
